version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: canyontest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=canyontest
      - DB_SSLMODE=disable
      - JWT_SECRET=your-jwt-secret-key
      - GITEA_BASE_URL=https://gitea.com
      - GITEA_CLIENT_ID=your-gitea-client-id
      - GITEA_CLIENT_SECRET=your-gitea-client-secret
      - GITEA_REDIRECT_URL=http://localhost:8080/oauth/callback

volumes:
  postgres_data: